version: '3.4'

services:
  jacarandacasadebrincar.api:
    image: ${DOCKER_REGISTRY-}jacarandacasadebrincarapi
    build:
      context: .
      dockerfile: src/JacarandaCasaDeBrincar.Api/Dockerfile
    environment:
        DBServer: "db"
    ports:
      - "9000:9000"
    depends_on: 
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password@12345"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
    - "14331:1433"