// <auto-generated />
using System;
using JacarandaCasaDeBrincar.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JacarandaCasaDeBrincar.Data.Migrations
{
    [DbContext(typeof(JacarandaDbContext))]
    [Migration("20210126225328_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("AllergieStudent", b =>
                {
                    b.Property<Guid>("AllergiesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AllergiesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("AllergieStudent");
                });

            modelBuilder.Entity("FoodRestrictionStudent", b =>
                {
                    b.Property<Guid>("FoodRestrictionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FoodRestrictionsId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("FoodRestrictionStudent");
                });

            modelBuilder.Entity("GuardianStudent", b =>
                {
                    b.Property<Guid>("GuardiansId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GuardiansId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("GuardianStudent");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Complement")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Addresses", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.Allergie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Allergies", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Campaigns", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.Capture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCapture")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FrequencyPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HowDidYouknowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InitialContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NextContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("FrequencyPackageId");

                    b.HasIndex("HowDidYouknowId");

                    b.HasIndex("InitialContactId");

                    b.HasIndex("NextContactId");

                    b.ToTable("Captures", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("PhoneOne")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("PhoneTwo")
                        .HasColumnType("varchar(14)");

                    b.HasKey("Id");

                    b.ToTable("Contacts", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.ContactType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("ContactTypes", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Function")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Rg")
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.ToTable("Employees", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.FoodRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("FoodRestrictions", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.FrequencyPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("FrequencyPackages", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.Guardian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyName")
                        .HasColumnType("varchar(250)");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<bool>("IsResponsable")
                        .HasColumnType("bit");

                    b.Property<string>("Kinship")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Occupation")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContactId");

                    b.ToTable("Guardians", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.HowDidYouknow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("HowDidYouknows", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.InitialContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContactTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAndHourFromContact")
                        .HasColumnType("datetime2");

                    b.Property<string>("Informations")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("ResponsibleEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeId");

                    b.HasIndex("ResponsibleEmployeeId");

                    b.ToTable("InitialContacts", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.NextContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContactTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAndHourFromContact")
                        .HasColumnType("datetime2");

                    b.Property<string>("Informations")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("ResponsibleEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeId");

                    b.HasIndex("ResponsibleEmployeeId");

                    b.ToTable("NextContacts", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Picture")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("Rg")
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.ToTable("Students", "jacaranda");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.UnauthorizedPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("UnauthorizedPeople", "jacaranda");
                });

            modelBuilder.Entity("StudentUnauthorizedPerson", b =>
                {
                    b.Property<Guid>("StudentsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnauthorizedPeopleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentsId", "UnauthorizedPeopleId");

                    b.HasIndex("UnauthorizedPeopleId");

                    b.ToTable("StudentUnauthorizedPerson");
                });

            modelBuilder.Entity("AllergieStudent", b =>
                {
                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.Allergie", null)
                        .WithMany()
                        .HasForeignKey("AllergiesId")
                        .IsRequired();

                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .IsRequired();
                });

            modelBuilder.Entity("FoodRestrictionStudent", b =>
                {
                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.FoodRestriction", null)
                        .WithMany()
                        .HasForeignKey("FoodRestrictionsId")
                        .IsRequired();

                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .IsRequired();
                });

            modelBuilder.Entity("GuardianStudent", b =>
                {
                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.Guardian", null)
                        .WithMany()
                        .HasForeignKey("GuardiansId")
                        .IsRequired();

                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .IsRequired();
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.Capture", b =>
                {
                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId");

                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.FrequencyPackage", "FrequencyPackage")
                        .WithMany()
                        .HasForeignKey("FrequencyPackageId");

                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.HowDidYouknow", "HowDidYouknow")
                        .WithMany()
                        .HasForeignKey("HowDidYouknowId");

                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.InitialContact", "InitialContact")
                        .WithMany()
                        .HasForeignKey("InitialContactId");

                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.NextContact", "NextContact")
                        .WithMany()
                        .HasForeignKey("NextContactId");

                    b.Navigation("Campaign");

                    b.Navigation("FrequencyPackage");

                    b.Navigation("HowDidYouknow");

                    b.Navigation("InitialContact");

                    b.Navigation("NextContact");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.Guardian", b =>
                {
                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.Navigation("Address");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.InitialContact", b =>
                {
                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.ContactType", "ContactType")
                        .WithMany()
                        .HasForeignKey("ContactTypeId");

                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.Employee", "ResponsibleEmployee")
                        .WithMany()
                        .HasForeignKey("ResponsibleEmployeeId");

                    b.Navigation("ContactType");

                    b.Navigation("ResponsibleEmployee");
                });

            modelBuilder.Entity("JacarandaCasaDeBrincar.Business.Models.NextContact", b =>
                {
                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.ContactType", "ContactType")
                        .WithMany()
                        .HasForeignKey("ContactTypeId");

                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.Employee", "ResponsibleEmployee")
                        .WithMany()
                        .HasForeignKey("ResponsibleEmployeeId");

                    b.Navigation("ContactType");

                    b.Navigation("ResponsibleEmployee");
                });

            modelBuilder.Entity("StudentUnauthorizedPerson", b =>
                {
                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .IsRequired();

                    b.HasOne("JacarandaCasaDeBrincar.Business.Models.UnauthorizedPerson", null)
                        .WithMany()
                        .HasForeignKey("UnauthorizedPeopleId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
